### PR TITLE
[Backport 8548] Fix viewport aspect caching

### PR DESCRIPTION
**Pull request by Connor-Bowley**
This brings back the performance updates made to VTK as well the fix to them.

### CODE REVIEW

**Review by lassoan — CHANGES_REQUESTED** [review]
Thanks a lot for the quick fix.

Please update the second commit message to follow the convention for backport commits (`[Backport MR-8548] ...`). This helps to ensure that no commits are missed when Slicer's VTK is synchronized with the VTK master.

**Comment by Connor-Bowley** [comment]
Updated

**Review by lassoan — APPROVED** [review]
perfect, thank you

**Comment by lassoan** [comment]
Updated Slicer's VTK to include these updates - https://github.com/Slicer/Slicer/commit/0b17794268a3d2c898b58f468a2a6649e9d3d73b

**Pull request merged**
