### PR TITLE
Slicer v9.0.20201111 733234c785 backport fixes

### PR DESCRIPTION
**Pull request by lassoan**
Merged back two fixes from VTK master.

### CODE REVIEW

**Comment by lassoan** [comment]
@jcfr would you like to review this or I can go on and merge?

**Comment by jcfr** [comment]
> would you like to review this or I can go on and merge?

Thanks for the ping. Having a look now

**Comment by jcfr** [comment]
Closing. Changes pushed to https://github.com/Slicer/VTK/tree/slicer-v9.0.20201111-733234c785 as https://github.com/Slicer/VTK/commit/c90cee638481a1c28c309bfad91d98c3d7d8e961 and https://github.com/Slicer/VTK/commit/1076d8bc00f12c49af4e35a3e0e58beae6ad361b


image

**Comment by lassoan** [comment]
Thank you @jcfr. Are you going to update the git hash in Slicer, too?

**Comment by jcfr** [comment]
> Are you going to update the git hash in Slicer, too?

Yes, here it is: https://github.com/Slicer/Slicer/pull/5520

**Comment by lassoan** [comment]
Thank you!

**Pull request closed without merging**
