### PR TITLE
COMP: add required header for vs2013 build

### PR DESCRIPTION
**Pull request by ihnorton**

### CODE REVIEW

**Comment by ihnorton** [comment]
Bump.

**Comment by ihnorton** [comment]
Bump. @jcfr @finetjul

**Comment by jcfr** [comment]
Thanks for the reminder. 

I created a topic on VTK gitlab for inclusion in the official repo.
See https://gitlab.kitware.com/jcfr/vtk/commits/algorithm-header-for-vs2013

Would be great if you could provide me with the build error details.

In the mean time, I will update the Slicer/VTK fork.

**Comment by jcfr** [comment]
Integrated in [r24110](http://viewvc.slicer.org/viewvc.cgi/Slicer4?view=revision&revision=24110)

**Comment by jcfr** [comment]
@ihnorton  To move forward with the VTK topic [1], having details about the error would be great. Thanks

[1] https://gitlab.kitware.com/jcfr/vtk/commits/algorithm-header-for-vs2013

**Comment by ihnorton** [comment]
It is not an issue on VTK master because [this commit](https://github.com/Slicer/VTK/commit/c6caae42407c075ec1c4d61a17f98fdddfe3d8530) is only on the Slicer branch. The error is `error C2039: 'max' : is not a member of 'std'`. Fix is the same as e.g. [here](http://www.vtk.org/pipermail/vtkusers/2013-November/081926.html).

**Comment by jcfr** [comment]
Makes sense. Thanks for the explanation.

Since I incorrectly assumed the problem was not specific to Slicer/VTK, I first looked at `vtkOpenGLGPUVolumeRayCastMapper.cxx` in regular VTK .. and couldn't find occurence of `std::min`, `std::max`, ... every is clear now.

**Pull request closed without merging**
