### PR TITLE
[slicer-v9.2.20230607-1ff325c54-2]  Backports related to Rendering & VR

### PR DESCRIPTION
**Pull request by jcfr**
# Testing

|                      |  Build of the VTK branch | Build of CTK       | Build of Slicer | Run Slicer |
|----------------------|--------------------------|--------------------|-----------------|---|
| `overload` / Windows | :white_check_mark:       | :white_check_mark: | :white_check_mark: | :white_check_mark:(*) |
| `computron` / macOS  | :white_check_mark:       | :white_check_mark:                    | :white_check_mark: | :white_check_mark:(*) |
| `metroplex` / Linux  | :white_check_mark:       | :white_check_mark: |:white_check_mark: | :white_check_mark:(*)|

_(*) A performance regression was identified while exercising the volume rendering module. Running `git bisect` (see https://github.com/Slicer/VTK/pull/46#issuecomment-1859502939) helped identify https://github.com/Kitware/VTK/commit/cff3d9a60 (vtkRenderer: Fix prop picking in GetZ method) as the culprit._

# List of changes related to Rendering & VR

## Slicer specific

* `[SlicerVirtualReality] ENH: Update OpenVR json binding to map right and left trigger with triggeraction`

### Features

* `Add ForceVerticalTitle option to vtkScalarBarActor` ([MR-10306](https://gitlab.kitware.com/vtk/vtk/-/merge_requests/10306))
  * [x] `Add ForceVerticalTitle option to vtkScalarBarActor` (kitware/VTK@fa6552eaf20739cfce5427b738fa5253ed437234)

* `vtkOpenGLPolyDataMapper: add line opacity control` ([MR-10307](https://gitlab.kitware.com/vtk/vtk/-/merge_requests/10307))
  * [x] `vtkOpenGLPolyDataMapper: add line opacity control` (kitware/VTK@28e580e159d6ffecc5a9d5777988f379580e9c5b)

### VR/OpenVR/OpenXR

* `XR: Move device pose update in interactor` ([MR-10742](https://gitlab.kitware.com/vtk/vtk/-/merge_requests/10742))  
  * [x] `XR: Move device pose update in interactor` (kitware/VTK@a155740b2aea8fcb5c09ee216c25805a28105a0e)

* `Overrideable vr interactions` [MR-10735](https://gitlab.kitware.com/vtk/vtk/-/merge_requests/10735)
  * [x] `VR: Add VTKIS_USCALE support in VR interactor style` (kitware/VTK@d1699eb07f7972dd367979830b8c31536dd73180)
  * [x] `VR: enable interaction methods to be overrideable` (kitware/VTK@dd2a56a51b3cd950e10bf877a4c0ed0da03a4752)

* `vtkModule: use FILE_SETs for header files` ([MR-10555](https://gitlab.kitware.com/vtk/vtk/-/merge_requests/10621))
  * [x] `Rendering/VR: make `glew` a public dependency` (kitware/VTK@d79eba443a7f5c87337bfa1a2750fdbe10fa83b0)

* `Add volume clipping to vtkVRInteractorStyle` ([MR-10555](https://gitlab.kitware.com/vtk/vtk/-/merge_requests/10555))
  * [x] `Add volume clipping to vtkVRInteractorStyle` (kitware/VTK@2904bb86a6a0aed07ebc3aec245cd428a9cc71e4)

* `OpenXR: Add missing EndInitialize in QueryInstanceVersion` ([MR-10550](https://gitlab.kitware.com/vtk/vtk/-/merge_requests/10550))
  * [x] `OpenXR: Add missing EndInitialize in QueryInstanceVersion` (kitware/VTK@b22f520f09e351ee5bb6d924b3f8679ea8d2cdac)

* `OpenXRRemoting: Streamline integration as plugin` ([MR-10449](https://gitlab.kitware.com/vtk/vtk/-/merge_requests/10449))
  * [x] `OpenXRRemoting: Streamline integration as plugin` (kitware/VTK@7c0474c1fc8613d571d9633208a9985c4c022a6a)

* `XR: Improve OpenXR instance management` ([MR-10543](https://gitlab.kitware.com/vtk/vtk/-/merge_requests/10543))
  * [x] `Add a utility function to query OpenXR instance version` (kitware/VTK@b46651d17814a66f0a70f72459ca23e0b25b7a46)
  * [x] `Enable switching from remoting XR runtime to default XR runtime dynamically` (kitware/VTK@d32293bd80a78490a063c8f2a08f2aa9894fad2c)

    * Revert the following commit to allow integrating the next two commits, the corresponding functionality is integrated in a subsequent backport:
      * [x] **Revert**: `[Backport MR-10449] OpenXRRemoting: Streamline integration as plugin`  (Slicer/VTK@abbbb1bc3a76e97ff2ea7428dd8bb3156efa5c36)

* `OpenXR: Generalize XrCheck and downgrade action suggestion to a debug output` ([MR-10450](https://gitlab.kitware.com/vtk/vtk/-/merge_requests/10450))
  * [x] `OpenXRRemoting: Using XrCheckOutput` (kitware/VTK@8eee12093efe6d5903212b31da6e147336ff1472)

    * Revert the following commits as corresponding equivalent changes integrated afterward:
      * [x] **Revert**: `[Backport MR-10450] OpenXR: Improve XrCheckOutput API fixing constness of level parameter` (Slicer/VTK@259459fe1901d46acd0bc8bfdd2e19f5f955d359)
      * [x] **Revert**: `[Backport MR-10450] OpenXRRemoting: Fix windows build using XrCheckOutput instead of XrCheckError` (Slicer/VTK@5c31352993bbcb8ef156881c9cd060d0eb4caa81)

* `Move teleportation to interaction modes` ([MR-10546](https://gitlab.kitware.com/vtk/vtk/-/merge_requests/10546))
  * [x] `Move teleportation to interaction modes` (kitware/VTK@8e8b0fef743812e0343c3e88e89c529a4e286e48)

* `Add teleportation to VR` ([MR-10509](https://gitlab.kitware.com/vtk/vtk/-/merge_requests/10509))
  * [x] `Add teleportation to VR` (kitware/VTK@179d0445aae1f7cf9381e61f3211453226c44018)

* `VR Renderer: Add cross markers at tip of controllers` ([MR-10478](https://gitlab.kitware.com/vtk/vtk/-/merge_requests/10478))
  * [x] `VR Renderer: Add cross markers at tip of controllers` (kitware/VTK@9014167f066459c08889c170b8096769feeaf7fa)

* `OpenXR: Support depth buffer composition layer` ([MR-10596](https://gitlab.kitware.com/vtk/vtk/-/merge_requests/10596))
  * [x] `OpenXR: Support depth buffer composition layer` (kitware/VTK@ac4a96d816b6b8c1fd79a28a5a7393cabb62f802)

* `vtkWin32OpenGLDXRenderWindow: Fix missing include` ([MR-10730](https://gitlab.kitware.com/vtk/vtk/-/merge_requests/10730))
  * [x] `vtkWin32OpenGLDXRenderWindow: Fix missing include` (kitware/VTK@82af107b62807abea93a94df06be63ee2be23cab)

* `Split vtkWin32OpenGLDXRenderWindow initialization` ([MR-10484](https://gitlab.kitware.com/vtk/vtk/-/merge_requests/10484))
  * [x] `Split vtkWin32OpenGLDXRenderWindow initialization` (kitware/VTK@50c861bf3b0ffb620adbb90b30196163da688b18)

### Rendering

* `SSAO for volumes` ([MR-10725](https://gitlab.kitware.com/vtk/vtk/-/merge_requests/10725))
  * [x] `Test SSAO pass with GPU raycast volume mapper` (kitware/VTK@1b496902584f5866903bacfe16e75aa302d93cca)
  * [x] `Expose volume opacity threshold in SSAO pass` (kitware/VTK@eb55fc702decc338f0fed3be880df1042ebcabda)
  * [x] `Support SSAO for volumes` (kitware/VTK@8773b02c3a27114a79bd95a3457d0e0fad5f497c)
  * [x] `Allow vtkOpenGLRenderPass subclasses to add information keys efficiently` (kitware/VTK@44e8f26d5d8685faad3f14f76529615a8d7c294c)

* `Allow to specify other formats for the ssao pass depth texture` ([MR-10644](https://gitlab.kitware.com/vtk/vtk/-/merge_requests/10644))
  * [x] `Allow to specify other formats for the ssao pass depth texture` (kitware/VTK@0f2025faf487fe6179ddb702905390a71bbc2720)

* `Fix normal mapping with edge visibility` ([MR-10705](https://gitlab.kitware.com/vtk/vtk/-/merge_requests/10705))
  * [x] `Fix normal mapping with edge visibility` (kitware/VTK@d43ab15f061c31ea9f8c300a7cc0e93d14a23bfd)

* `Add VTK::ComputeLighting::Exit tag for volume shader replacement` ([MR-10645](https://gitlab.kitware.com/vtk/vtk/-/merge_requests/10645))
  * [x] `Add VTK::ComputeLighting::Exit tag for volume shader replacement` (kitware/VTK@2e94e8048de45d933747905e4ce6887731212101)

* `Allow volumes to write to the depth buffer` ([MR-10642](https://gitlab.kitware.com/vtk/vtk/-/merge_requests/10642))
  * [x] `Allow volumes to write to the depth buffer` (kitware/VTK@1995c65b536482faff482d7918e0871d92c869ac)

* `Optimize out unncessary OpenGL state queries` ([MR-10646](https://gitlab.kitware.com/vtk/vtk/-/merge_requests/10646))
  * **No backport: CONFLICT** [ ] `OpenGL: Optimize out unnecessary query for buffer size` (kitware/VTK@d75b9ab60ad)
  * [x] `ReadPixels: Check for errors only when VTK is configured to report errors` (kitware/VTK@3bd2e8384cf)

* `Point gaussian improvements` ([MR-10636](https://gitlab.kitware.com/vtk/vtk/-/merge_requests/10636))
  * [x] `Rename scale option and scale in the shader` (kitware/VTK@91629591f424c2791f5b98d31cc379148e03716d)
  * [x] `Use quad instead of triangle to bound the gaussian splat` (kitware/VTK@6ed84cad845f2a3decd01217e7bc61ff869c019a)
  * [x] `Use index array for point gaussians` (kitware/VTK@9d6f6277ff94864bbdfaa957f02be68073b03460)

* `RenderingOpenGL2: Fixed final blending of vtkOrderIndependentTranslucentPass.` ([MR-10603](https://gitlab.kitware.com/vtk/vtk/-/merge_requests/10603))
  * [x] `RenderingOpenGL2: Fixed final blending of vtkOrderIndependentTranslucentPass.` (kitware/VTK@fb2231815ca187a120f817fcef7af5864ed7ca75)

* `Glyph3DMapper: Fix display attribute inheritance logic` ([MR-10541](https://gitlab.kitware.com/vtk/vtk/-/merge_requests/10541))
  * [x] `Glyph3DMapper: Fix display attribute inheritance logic` (kitware/VTK@6dc5382e2a36f39537f592fc531589825ed95c8f)

* `vtkOpenGLES30PolyDataMapper: Remove override for ReplaceShaderCoincidentOffset` ([MR-10521](https://gitlab.kitware.com/vtk/vtk/-/merge_requests/10521))
  * [ ] `vtkOpenGLES30PolyDataMapper: Remove override for ReplaceShaderCoincidentOffset` (kitware/VTK@cc0de41691abe87851adf5d135c760e3cc0e5db6)

* `Support 4-component RGBA inputs for multivolume` ([MR-10477](https://gitlab.kitware.com/vtk/vtk/-/merge_requests/10477))
  * [x] `Test vtkMultiVolume with RGBA input and gradient opacity function` (kitware/VTK@129c55c5ccdddc3ae17e1fd842c139d70c008a42)
  * [x] `Update vtkMultiVolume doc to mention RGBA support` (kitware/VTK@9db07b46a2318a4093ad03730cfae3ed8a0e9faa)
  * [x] `Test multivolume with RGBA inputs` (kitware/VTK@97ba1fb9efea801b6a498a6c6fc2b85714f0c702)
  * [x] `Support 4-component RGBA inputs for multivolume` (kitware/VTK@bf461af88432e6f9eb7dc700d1355e21a06d6f4e)

* `Dolly3D: Remove incorrect check in Y axis only` ([MR-10435](https://gitlab.kitware.com/vtk/vtk/-/merge_requests/10435))
  * [x] `Dolly3D: Remove incorrect check in Y axis only` (kitware/VTK@375524370349e66995e40a77e55268ef03e0401e)

* `rendering: Do not offset vertices for drawing polygon edges` ([MR-10403](https://gitlab.kitware.com/vtk/vtk/-/merge_requests/10403))
  * [x] `rendering: Do not offset vertices for drawing polygon edges` (kitware/VTK@2fe546cc4934c476015bb88d5597a55044d60cd7)

* `vtkRenderer: Fix prop picking in GetZ method` ([MR-10391](https://gitlab.kitware.com/vtk/vtk/-/merge_requests/10391))
  * [x] `vtkRenderer: Fix prop picking in GetZ method` (kitware/VTK@cff3d9a6050f3d97493fba406ba488d87e1a4f08)

* `Document FrameBlitMode in vtkOpenGLRenderWindow.` ([MR-10341](https://gitlab.kitware.com/vtk/vtk/-/merge_requests/10341))
  * [x] `Apply 1 suggestion(s) to 1 file(s)` (kitware/VTK@b61cc84a25d8173535636d6ef18f878b18429d31)
  * [x] `Document FrameBlitMode in vtkOpenGLRenderWindow.` (kitware/VTK@7676b6acb57aba7bc49c942e9419ed9b0bf1f860)

* `Add missing SIZE_HINT on vtkImageActor::GetDisplayBounds` ([MR-10311](https://gitlab.kitware.com/vtk/vtk/-/merge_requests/10311))
  * [x] `Add missing SIZE_HINT on vtkImageActor::GetDisplayBounds` (kitware/VTK@4b14422e1dd119616067829b24f4113ac34e7120)

* `Fix abi namespace` ([MR-10269](https://gitlab.kitware.com/vtk/vtk/-/merge_requests/10343))
  * [x] `ABI: fix vtkOpenGLBatchedPolyDataMapper` (kitware/VTK@f58faae4791702c3f071eda910e00b17f6ce537f)
  * [x] `ABI: fix vtkCompositeSurfaceLICMapper` (kitware/VTK@28ecc8b66df2eff1009a18843704025bdc0475e5)
  * **No backport: CONFLICT** `ABI: fix vtkFieldDataToDataSetAttribute` (kitware/VTK@f0e61afd4784b29acadb528c8b941b13c456e3ca)
  * [x] `ABI: fix vtkValueFromString` (kitware/VTK@0d1d8526996239be333f37844d756dce051ee54d)

* `Support any texture with interpolate scalars` ([MR-10271](https://gitlab.kitware.com/vtk/vtk/-/merge_requests/10271))
  * [x] `Remove the TestBlockOpacity test` (kitware/VTK@cc2498c595f7daf436efbb35352e3a45b58f862d)
  * [x] `Support both texture and interpolated scalars in composite polydata mapper` (kitware/VTK@00a170ca4a35e06dee2c96f4b1bbd875afc9d383)
  * [x] `Support both texture and interpolated scalars in GLES polydata mapper` (kitware/VTK@9925fd1925a85eb40590de01ee56ee0c2f54f9da)
  * [x] `Add tests for texture coloring with interpolated scalars` (kitware/VTK@3db581f4f420875e16a0b7c8cf9cf84c764f3d84)
  * [x] `Support any texture with interpolate scalars ` (kitware/VTK@79969286ea2d9ecb54f11daa9cec96cdb0d2e9ec)

* `SurfaceWithEdges: Fix mixed geometry rendering` ([MR-10269](https://gitlab.kitware.com/vtk/vtk/-/merge_requests/10269))
  * [x] `SurfaceWithEdges: Fix mixed geometry rendering` (kitware/VTK@13e28a944ea1ebf3a59ec625e86341aba6bee301)

### CODE REVIEW

**Comment by jcfr** [comment]
cc: @LucasGandel @sankhesh @lassoan @pieper @sjh26

**Comment by jcfr** [comment]
Volume rendering seems much slower with these backports ... I am not yet[^1] sure if a performance regression was introduced and later fixed in a commit I did not integrate.

[^1]: I will do a local experimental build against VTK master to confirm this.

**Comment by jcfr** [comment]
After running a bisect, I ended up identifying the faulty commit as being d8cacb22db1f95a70f58c47449e71045f483f7c6 introduced in upstream as https://github.com/Kitware/VTK/commit/cff3d9a6050f3d97493fba406ba488d87e1a4f08 through [MR-10391](https://gitlab.kitware.com/vtk/vtk/-/merge_requests/10391) and intended to fix VTK issue [18503](https://gitlab.kitware.com/vtk/vtk/-/issues/18503).


image

**Comment by lassoan** [comment]
Great detective work @jcfr. Make sure the VTK team is aware of the issue - they would probably want to revert the commit or do further investigation (and for this the test that you created for the bisect could be very useful).

**Comment by jcfr** [comment]
> the test that you created for the bisect could be very useful

The process was manual. Enabling the volume rendering of `MRHead` (with `MR-Default` preset)  and interacting with the 3D view was slow on my workstation.

This is likely explained by how we make sure of `vtkWorldPointPicker::Pick`, see more details at https://github.com/Slicer/Slicer/pull/7487#issuecomment-1859573883

**Comment by jcfr** [comment]
@lassoan As the original contributor of `vtkMRMLThreeDViewInteractorStyle::QuickPick` and `vtkMRMLInteractionEventData::SetAccuratePicker` in Slicer/Slicer@364ff7b6d4758629b8659712fdec990d8bddd81b, it would be great if you could review VTK issue 18503[^1] and its associated MR-10391[^2]. This help us building a case for either reverting or updating the `vtkRenderer` API.

One potential approach is to consider adding a boolean parameter to the existing `vtkRenderer::GetZ()` method. Alternatively, we could also introduced a new method like `vtkRenderer::GetAccurateZ()`.

[^1]: https://gitlab.kitware.com/vtk/vtk/-/issues/18503
[^2]: https://gitlab.kitware.com/vtk/vtk/-/merge_requests/10391

**Comment by jcfr** [comment]
@lassoan @pieper 

Also, since in itself this branch is ready for integration, I would appreciate an approval.

Since the commit introducing the "regression" as been identified and reverted, we will work on addressing the `vtkRenderer::GetZ` issue later.

**Comment by lassoan** [comment]
I've posted to the VTK merge request here: https://gitlab.kitware.com/vtk/vtk/-/merge_requests/10391#note_1459483
Should we reopen the issue or enter a new issue as well (as a comment in a closed MR is very easy to ignore)?

**Comment by lassoan** [comment]
> Also, since in itself this branch is ready for integration, I would appreciate an approval.

Approved. Reviewing 55 commits in detail would be very time consuming, so I only had a quick look at the commit headlines. I was just wondering why do we manage so many backported changes. Could we use a more recent VTK release and have maybe just a couple of Slicer-specific patches?

**Comment by jcfr** [comment]
> I was just wondering why do we manage so many backported changes.

Considering the end of the year & the fact I have to integrate some of the recent Rendering changes along with the one related to OpenXR & OpenXRRemoting, it was easier to select the few commits specific to rendering and VR/XR.

In a nutshell, I preferred to only introduce selected "critical" changes and avoid to deal with side effects of VTK build-system updates and alike (yet).

> Could we use a more recent VTK release and have maybe just a couple of Slicer-specific patches?

This will be done earlier next year.

To clarify, the only Slicer specific changes are these ones and beside of 2e913288d5 introduced few days ago and specific to `SlicerVirtualReality`, there is nothing Slicer specific to review.

* 2e913288d5 - `[SlicerVirtualReality] ENH: Update OpenVR json binding to map right and left trigger with triggeraction`
* 6d0bf9edbb - `[SlicerSMTK] vtkm: Use github.com/KitwareMedical/vtk-m: Update diy install rules, support TBB_DIR`
* 4d6dfb220b - `[SlicerSMTK] COMP: Add support for specifying vtk-m library install components`
* 8b22157d2c - `[Slicer] COMP: Remove FindTBB and expect VTK to be configured with TBB_DIR`
* c82e337ac0 - `[Slicer] BUG: Update vtkPythonUtil to disable relative import causing crash for Slicer modules`
* aea1f4438c - `[Slicer] COMP: Remove custom FindOpenGL to ensure OpenGL_GL_PREFERENCE is considered`

.. from which these one have already been integrated upstream through [MR-10400](https://gitlab.kitware.com/vtk/vtk/-/merge_requests/10400):

* 0227875f00 - `[SlicerVirtualReality] BUG: Ensure a valid OpenVR pose is returned`
* c6189a4a27 - `[SlicerVirtualReality] ENH: Re-introduce OpenVR API for retrieving last OpenVR pose`

and this one was just to avoid a false positive:

* a3ab617b0f - `[Slicer] COMP: Empty commit to workaround CTest false positive`

**Comment by jcfr** [comment]
> Reviewing 55 commits in detail would be very time consuming

Agreed. 

And, as you mentioned, having a quick look is the way to go.

To put things in perspective, when I update VTK or ITK, I also go through the list of changes introduced between version doing a  **cursory review**. As you noted, looking at each one of them in details would not be feasible.

This set of backported changes is not much different from a regular version update. The advantage in this case is that it allowed to fairly efficiently identify a regression through `git bisect`.

**Comment by lassoan** [comment]
All sounds good, thank you.

**Pull request merged**
