### PR TITLE
[slicer-v9.2.20230607-1ff325c54-2][Backport MR-11403] ENH: Add alpha blending option for the blending filter

### PR DESCRIPTION
**Pull request by Punzo**
Reference PRs:
https://gitlab.kitware.com/vtk/vtk/-/merge_requests/11403
https://github.com/Slicer/Slicer/pull/7886

### CODE REVIEW

**Review by lassoan — COMMENTED** [review]
Thank you! To make consolidation of backported patches easier in the future, please include the MR number (preferably in the subject line of the commit).

**Comment by jcfr** [comment]
For example:

image

Also make sure to use `Backport` instead of `backport` :pray:

**Comment by Punzo** [comment]
@jcfr @lassoan  Done!

btw: in the commit I had written only backport because the upstream VTK PR was already merged and I was just following the Readme of this repo:

image

maybe it is worth to remove/change the second part from the README.

**Comment by lassoan** [comment]
I did not know about this distinction between already merged and not yet merged MRs.

@jcfr are the instructions up-to-date? What's the reason for the difference in the commit comments? It would good to have as simple procedures as possible.

**Comment by lassoan** [comment]
I'm merging this now to allow to proceed.

**Comment by Punzo** [comment]
> I'm merging this now to allow to proceed.

thanks!

**Comment by jcfr** [comment]
> distinction between already merged and not yet merged MRs

@lassoan 

This helpful when working on updating VTK, it allows to check if the associated MR has effectively been integrated.

@Punzo 

Thanks for updating the pull request

**Pull request merged**
