### PR TITLE
ENH: Add shading to multi-volume rendering

### PR DESCRIPTION
**Pull request by cpinter**
- Add lighting computation to multi-volume case
- Use per-volume lighting directions

Co-authored-by: Kyle Sunderland <1krs1@queensu.ca>

### CODE REVIEW

**Comment by cpinter** [comment]
Some features still don't work for m ulti-volume such as cropping with ROI, but at least we have shading now.

This PR allows us to have this in Slicer. Any suggestions how to proceed? PR in VTK master? @lassoan @pieper @jcfr

**Comment by jcfr** [comment]
This is outstanding :pray: 

> PR in VTK master?

That would be great. On my side, I will make sure the team is aware that review will be needed.

**Comment by pieper** [comment]
Nice work!  💯   

A PR to VTK makes perfect sense.  But if we think it will take more than a few days I'd love to see this merged into our version.

**Comment by jcfr** [comment]
>  But if we think it will take more than a few days I'd love to see this merged into our version.

Just to let you know that without having a MR against the latest VTK, the feature may be discarded this week or the following as I started to work on VTK9 integration. This is why creating a MR request against upstream is critical.

Since I anticipate it will take few iterations for the merge request to land in upstream VTK, we will still have our Slicer/VTK fork where we could backport the MR ... but we would need it to be based of the latest version of VTK.

**Comment by cpinter** [comment]
OK I'll create an MR in VTK. If it doesn't screw things up we can still merge this and start testing in Slicer for the time being!

**Comment by sankhesh** [comment]
@cpinter This is great! Feel free to tag me on the upstream VTK MR and I can help test/review.

**Comment by cpinter** [comment]
I took a quick look at these files in VTK master, and merging will be non-trivial. I'll try to get it done soon though.

**Comment by lassoan** [comment]
This is awesome @cpinter, I'm really looking forward to have proper multi-volume rendering capabilities in Slicer!

Just out of curiosity, was there any interesting bug or special trick that you had to implement to make it work?

**Comment by cpinter** [comment]
The final issue was found by @Sunderlandkyl (in terms of the SpineUs project): https://github.com/Sunderlandkyl/VTK/commit/aa75bb235d15943498c42fe35100d492b373c616

Initialization of the scalar range was done improperly and was undeterministic.

**Comment by cpinter** [comment]
I think I managed to merge the changes into VTK master. My issue is that I don't know how to test it. VTK master cannot be built against Slicer yet, and the VTK tests don't seem to work. If I start `vtkRenderingVolumeCxxTests` then select the test I want (#46), then the test fails with "Error opening file ..." errors. Actually, any other test that requires data fails. Is there something special needed for these external data files to be loaded correctly? It seems they are downloaded dynamically but I can't find any info on it, and not sure what is missing. Thanks!

**Comment by sankhesh** [comment]
@cpinter It seems like your VTKExternalData might not be set up. Did you run `Utilities/SetupForDevelopment.sh` in the VTK source tree?

Secondly, if you push your changes and create a MR on https://gitlab.kitware.com/vtk/vtk, we can also test on the dashboards.

**Comment by cpinter** [comment]
Thanks! I ran SetupForDevelopment but no success yet. I'll create the MR and also keep trying.

**Comment by cpinter** [comment]
https://gitlab.kitware.com/vtk/vtk/-/merge_requests/7083

**Comment by cpinter** [comment]
@jcfr The VTK MR has been merged, see https://gitlab.kitware.com/vtk/vtk/-/merge_requests/7092
Can we backport the change? Thank you!

**Comment by cpinter** [comment]
@jcfr Would it be possible to backport this commit from VTK please? I did what you asked and now it is in VTK proper, and the only step necessary to have a significantly improved multi-volume rendering in Slicer is to backport this change. Thank you!

**Comment by jcfr** [comment]
Thanks foe your patience. Will het to that shortly. 🙏

**Comment by cpinter** [comment]
Just a friendly reminder again about the backporting. I'd need to make a release with shading of multiple volumes, now a supposedly simple change after having everything ready to pick this commit to Slicer/VTK. Can I help with this in any way? Thanks!

**Comment by lassoan** [comment]
@cpinter you can backport the changes yourself - see https://github.com/Slicer/VTK#how-to-update-the-version-of-vtk-

**Comment by jcfr** [comment]
@cpinter  Thanks for adding the changes to upstream VTK, that is outstanding. 

Now, as indicated by @lassoan , if you add the changes on top of the branch https://github.com/Slicer/VTK/tree/slicer-v8.2.0-2018-10-02-74d9488523 and push a branch on your own fork, we can take care of the rest. 

Thanks so much 🙏

**Comment by cpinter** [comment]
@jcfr @lassoan Here is the backport PR: https://github.com/Slicer/VTK/pull/31

I hope this is fine! Thanks a lot!

**Comment by jcfr** [comment]
Closing. This is superseded by https://github.com/Slicer/VTK/pull/31

**Pull request closed without merging**
