### PR TITLE
BUG: Fix generation of volume rendering shader

### PR DESCRIPTION
**Pull request by jcfr**
Follow-up of 3e45140d5 (BUG: use alpha to calculate RGBA lighting) removing use of regex leading to segfault in binary compiled using gcc 7.3.1. See https://github.com/Slicer/Slicer/issues/7281

Instead of using regex replacement it introduce an ivar called lightingComponent set based on the value of "independentComponents".

### CODE REVIEW

**Review by lassoan — APPROVED** [review]
Looks good to me. Have you been able to test if it fixes the issue?

**Comment by jcfr** [comment]
I confirmed that enabling volume rendering does not crash anymore.

I now need to confirm that the use of the colorize module also work.

For reference, see also https://discourse.slicer.org/t/vtk-multivolume-cinematic-volume-rendering/31981/44?u=jcfr

**Comment by lassoan** [comment]
> I confirmed that enabling volume rendering does not crash anymore.

Awesome!

**Comment by pieper** [comment]
Nice!  🙏

**Pull request merged**
