### PR TITLE
Slicer v8.2.0 2018 10 02 74d9488523

### PR DESCRIPTION
**Pull request by cpinter**
Backport of the multi-volume shading work from VTK master. I tested it on Windows.

### CODE REVIEW

**Comment by jcfr** [comment]
Thanks 🙏 

Testing on Linux

**Comment by jcfr** [comment]
Closing. Changes backported in https://github.com/Slicer/VTK/commit/09a6d768eca08bd71e161257f7459fc127357429 and https://github.com/Slicer/VTK/commit/9c813fe590b5f604dbd7f6641021308a21b3cea1

**Comment by jcfr** [comment]
Corresponding Slicer PR is https://github.com/Slicer/Slicer/pull/5091

**Comment by cpinter** [comment]
Thanks a lot, @jcfr !

**Pull request closed without merging**
