### PR TITLE
BUG: WIP: fix vtkPickingManager interaction with widgets

### PR DESCRIPTION
**Pull request by pieper**
Adds options to explicitly enable and disable vtkAbstractPickers
so that the can be excluded from vtkPickingManager evaluations.

Updates vtkWidgetRepresentation so it can be told by when to
enable and disable any internally managed pickers.

Fixes the one class of pickers used in slicer so that version
4.4 can be released.

WIP: The changes in this commit should be evaluated in terms
of the vtk widget design and possibly picking can be automatically
handled as a byproduct of other calls such that EnablePicking and
DisablePicking are not needed in the public API.

See [1] for more discussion of the problem, along with a python
script that replicates the core issue that caused problem in slicer,
but using pure VTK.

http://na-mic.org/Bug/view.php?id=3808

### CODE REVIEW

**Comment by pieper** [comment]
@jcfr - I'm not clear on how the branches are set up here - when I tried a pull request to the master there were a lot of changes, so I believe we want to cherry pick this into a new branch to use for slicer 4.4?

**Comment by jcfr** [comment]
@pieper  when doing a request, you can change the base. In your case it should be `Slicer:slicer-v6.2.0-7167ad1_2014-08-21_v2`. It seems you figured it out. I will integrate this request

**Comment by pieper** [comment]
Yes, thanks - I did base off of that, but did think it it should be merged back into a branch with a specific version name.  Anyway, glad that worked!

**Comment by jcfr** [comment]
Updated in  [r23650](http://viewvc.slicer.org/viewvc.cgi/Slicer4?view=revision&revision=23650).

Otherwise, the branch name `slicer-v6.2.0-7167ad1_2014-08-21_v2`means:
- `slicer` specific branch
- based of VTK `v6.2.0` at commit kitware/VTK@7167ad1 from 2014-08-21
- the `v2` simply means that I re-organize the Slicer specific commits compare to a first version of the topic that was already referencing by a Slicer commit.

**Comment by pieper** [comment]
I got you - makes sense now.  Nice!

**Pull request merged**
