### PR TITLE
Allow pyvtkObjects to have InvokeEvent called on them with calldata

### PR DESCRIPTION
**Pull request by HastingsGreer**
permitted calldata types in python: strings, floats, ints, vtk.vtkObjects

### CODE REVIEW

**Comment by HastingsGreer** [comment]
tested locally, works for all types except vtkObjects. The pythonOverload class cannot handle vtkObjects in this version of VTK, so vtkObject support will have to wait until we catch up with vtk master

**Comment by HastingsGreer** [comment]
@jcfr

**Comment by jcfr** [comment]
Thanks :+1: 

Integrated in https://github.com/Slicer/VTK/commit/f08b7db25fc76c0c256e040835e9aa8426a18c7c

**Comment by jcfr** [comment]
Integrated in Slicer as [r25177](http://viewvc.slicer.org/viewvc.cgi/Slicer4?view=revision&revision=25177)

**Pull request closed without merging**
